{% set python_min = "3.10" %}
{% set name = "fscan" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fscan-{{ version }}.tar.gz
  sha256: fdb44f292612b873937ea7d8af77ec7885a2a44839413442d957426497372c39

build:
  entry_points:
    - FscanDriver = fscan:__main__.main
    - postProcess = fscan:post.main
    - AnalysisSummary = fscan:status.main
    - clean = fscan:clean.main
    - FscanFineToothPlot = fscan.plot.finetoothplot:main
    - FscanStaticPlot = fscan.plot.static:main
    - FscanAutoTag = fscan.process.autotag:main
    - FscanDTutils = fscan.utils.dtutils:main
    - FscanSummaryPage = fscan:html.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.3
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - bokeh
    - gwdetchar
    - gpstime

test:
  imports:
    - fscan
  commands:
    - pip check
    - FscanDriver --help
    - postProcess --help
    - AnalysisSummary --help
    - clean --help
    - FscanFineToothPlot --help
    - FscanStaticPlot --help
    - FscanAutoTag --help
    - FscanDTutils --help
    - FscanSummaryPage --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fscan/
  summary: Fscan tool for monitoring narrow spectral artifacts in LIGO data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
