{% set name = "fscan" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fscan-{{ version }}.tar.gz
  sha256: 20c5e88e15193bc262f135a63dda6b3bff132f8809da08da613249f46ba92944

build:
  entry_points:
    - FscanDriver = fscan:__main__.main
    - postProcess = fscan:post.main
    - AnalysisSummary = fscan:status.main
    - clean = fscan:clean.main
    - FscanFineToothPlot = fscan:plot.finetoothplot.main
    - FscanStaticPlot = fscan:plot.static.main
    - FscanAutoTag = fscan:process.autotag.main
    - FscanDTutils = fscan:utils.dtutils.main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - bokeh
    - gwdetchar
    - pycondor

test:
  imports:
    - fscan
  commands:
    - pip check
    - FscanDriver --help
    - postProcess --help
    - AnalysisSummary --help
    - clean --help
    - FscanFineToothPlot --help
    - FscanStaticPlot --help
    - FscanAutoTag --help
    - FscanDTutils --help
  requires:
    - pip

about:
  home: https://pypi.org/project/fscan/
  summary: Fscan tool for monitoring narrow spectral artifacts in LIGO data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
